export const IS_LOGGED_IN = 'IS_LOGGED_IN'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const GET_DRIVERS = 'GET_DRIVERS'
export const ADD_DRIVER = 'ADD_DRIVER'
export const UPDATE_DRIVER = 'UPDATE_DRIVER'
export const REMOVE_DRIVER = 'REMOVE_DRIVER'